---
title: "INFLUENCE OF FEMALE EDUCATION ON FERTILITY RATE ACROSS COUNTRIES"
format: dashboard
author: Fayomi Abigail Oludayo 
jupyter: python3
execute:
    echo: false
dashboard:
    expand: false
---

```{python}
import pandas as pd
import plotly.express as px


education = pd.read_csv("data/female_education.csv")
education = education.rename(columns={"name": "country"})
education = education.melt(
    id_vars=["geo", "country"],
    var_name="year",
    value_name="education"
)
education["year"] = pd.to_numeric(education["year"], errors="coerce")
education["education"] = pd.to_numeric(education["education"], errors="coerce")
education = education.dropna(subset=["year", "education"])
education["year"] = education["year"].astype(int)


fertility = pd.read_csv("data/fertility_rate.csv")
fertility = fertility.rename(columns={"name": "country"})
fertility = fertility.melt(
    id_vars=["geo", "country"],
    var_name="year",
    value_name="fertility"
)
fertility["year"] = pd.to_numeric(fertility["year"], errors="coerce")
fertility["fertility"] = pd.to_numeric(fertility["fertility"], errors="coerce")
fertility = fertility.dropna(subset=["year", "fertility"])
fertility["year"] = fertility["year"].astype(int)


population = pd.read_csv("data/population.csv")
population = population.rename(columns={"name": "country"})
population = population.melt(
    id_vars=["geo", "country"],
    var_name="year",
    value_name="population"
)
population["year"] = pd.to_numeric(population["year"], errors="coerce")
population["population"] = pd.to_numeric(population["population"], errors="coerce")
population = population.dropna(subset=["year", "population"])
population["year"] = population["year"].astype(int)


df = education.merge(
    fertility,
    on= ['geo', 'country', 'year'],
    how= 'inner'
)
df = df.merge(
    population,
    on= ['geo', 'country', 'year'],
    how= 'inner'
)
df = df[(df['year']>=1960) & (df['year']<= 2020)]

fig1 = px.scatter(
    df,
    x="education",
    y="fertility",
    size="population",
    hover_name="country",
    animation_frame="year",
    title="Education vs Fertility Over Time",
    labels={
        "education": "Female Education (Years)",
        "fertility": "Fertility Rate"
    }
)


filtered_df = df[df["year"] == 2007]
fig2007 = px.scatter(
    filtered_df,
    x="education",
    y="fertility",
    size="population",
    hover_name="country",
    hover_data={"population":":,.0f"},
    title=f"Education vs Fertility in {2007}",
    labels={
        "education": "Female Education (Years)",
        "fertility": "Fertility Rate"
    }
)
education_trend = df.groupby("year", as_index=False)["education"].mean()
edu = px.line(
    education_trend,
    x="year",
    y="education",
    title="Average Female Education Over Time"
)


fertility_trend = df.groupby("year", as_index=False)["fertility"].mean()
fert = px.line(
    fertility_trend,
    x="year",
    y="fertility",
    title="Average Fertility Over Time"
)


selected_year = 2007
filtered_df = df[df["year"] == selected_year]
top_education = filtered_df.nlargest(10, "education")
top_edu = px.bar(
    top_education,
    x="education",
    y="country",
    orientation = 'h',
    color_discrete_sequence=["skyblue"],
    title=f"Top 10 Countries by Female Education in {selected_year}"
).update_yaxes(categoryorder="total ascending")


top_fertility = filtered_df.nlargest(10, "fertility")
top_fert = px.bar(
    top_fertility,
    x="fertility",
    y="country",
    orientation = 'h',
    color_discrete_sequence=["skyblue"],
    title=f"Top 10 Countries by Fertility in {selected_year}"
).update_yaxes(categoryorder="total ascending")


countries_to_compare = ["Nigeria", "Canada", "Niger", "Switzerland", "Germany"]

compare_df = df[df["country"].isin(countries_to_compare)]

compare_edu = px.line(
    compare_df,
    x="year",
    y="education",
    color="country",
    title="Education Comparison Over Time"
)

compare_fert = px.line(
    compare_df,
    x="year",
    y="fertility",
    color="country",
    title="Fertility Comparison Over Time"
)

selected_year = 2007
filtered_df = df[df["year"] == selected_year]

avg_education = round(filtered_df["education"].mean(), 2)
avg_fertility = round(filtered_df["fertility"].mean(), 2)
total_population = round(filtered_df["population"].sum() / 1e9, 2)

highest_population_country = filtered_df.loc[filtered_df["population"].idxmax(), "country"]
highest_population_value = filtered_df["population"].max()

highest_fertility_country = filtered_df.loc[filtered_df["fertility"].idxmax(), "country"]
highest_fertility_value = filtered_df["fertility"].max()

highest_education_country = filtered_df.loc[filtered_df["education"].idxmax(), "country"]
highest_education_value = filtered_df["education"].max()
```




# HOME

Using global development data, the analysis explores how increasing access to education may influence population growth and demographic change. This page shows the trends and patterns in education, fertility, and population levels for the year 2007, providing insights into the global state of these key indicators.


## ROW {height="30%"}

::: {.valuebox icon= "heart" color="#1E90FF" title="Average education"}
`{python} str{avg_education}`

`{python} {highest_education_country}`
:::

::: {.valuebox icon= "heart" color="#7e77e4" title="Average fertility"}
`{python} str{avg_fertility}`

`{python} {highest_fertility_country}`
:::

::: {.valuebox icon= "graph-up" color="#1efff4" title="Total population"}
`{python} str{total_population}`

`{python} {highest_population_country}`
:::

## ROW {height="70%"}

### {width="50%"}

```{python}
fig1
```


### {width="50%"}

```{python}
fig2007
```


Countries with higher levels of female education tend to have lower fertility rates. This suggests a strong negative relationship between education and the number of children per woman.


# TRENDS

**Global Trends**

This section examines how female education and fertility rates have changed over time across countries.

The visualizations show that as access to education for women has increased globally, fertility rates have generally declined. This pattern highlights the important role education plays in shaping demographic and social development.


## Row {height=60%}

### {width="50%"}

```{python}
edu
```

### {width=50%}

```{python}
fert
```


# RANKINGS

**Country Rankings**

This section highlights the top countries with the highest female education levels and the highest fertility rates in the selected year.

By comparing these rankings, it becomes easier to see how countries with higher education levels for women often experience lower fertility rates, while countries with limited access to education tend to have higher fertility levels.

## Row 1 {height=50%}

### {width=50%}

```{python}
top_edu
```


## Row 2 {width=50%}

```{python}
top_fert
```



# YEARLY TREND

This section explores how the relationship between female education and fertility rates in selected countriesevolves across years.

The visualization illustrates how these countries move over time as education levels increase and fertility rates decrease, showing long-term global demographic changes.

## Row {height=80%}

### {width="40%"}
```{python}
compare_edu
```

### {width="30%"}
```{python}
compare_fert
```


# COUNTRY COMPARISON

By comparing countries, the dashboard highlights how differences in educational opportunities for women can influence fertility patterns and population growth.

## Row {height=80%}

```{python}
fig1
```


# DATA SOURCES

```{python}
itables.show(
    df,
    caption="Full Tips Dataset",
    buttons=["csvHtml5"]
)
```

# ABOUT

This dashboard analyzes the relationship between **female education** levels, **fertility rates** and **population** across countries from **1960** to **2020**. The goal of the project is to explore how improvements in women's education may influence population growth and demographic change globally.

The analysis combines multiple datasets on female education, fertility rates, and population to examine both global trends and country-level differences. Through interactive visualizations, the dashboard highlights how increases in education are often associated with lower fertility rates across many regions.

**Tools and Technologies**

- This project was developed using the following tools:

- Python for data analysis

- Pandas for data cleaning and transformation

- Plotly for interactive data visualizations

- Quarto for building the interactive dashboard

- GitHub for version control and project sharing

**Key Features**

The dashboard includes several components to explore the data:

- **Key indicators** summarizing education, fertility, and population levels

- **Scatter plots** showing the relationship between education and fertility

- **Trend analysis** illustrating changes over time

- **Country rankings** highlighting the highest education and fertility levels

- **Country comparisons** to analyze differences between nations

**Learning Objective**

This project was created as part of my learning journey in Python and data visualization, with the goal of building practical skills in:

- data cleaning and transformation

- merging and reshaping datasets

- building interactive visualizations

- designing analytical dashboards






